apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopping-app
  template:
    metadata:
      labels:
        app: shopping-app
    spec:
      containers:
      - name: shopping-app
        image: 221032952239.dkr.ecr.us-east-1.amazonaws.com/shopping-site:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-service
spec:
  type: LoadBalancer
  selector:
    app: shopping-app
  ports:
    - port: 80
      targetPort: 80
